# vi:set ft=sh:
[[ -e "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -f $HOME/.bash_profile.local ]] && source $HOME/.bash_profile.local


[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
