# vi:set ft=sh:

[[ -f "$HOME/.profile" ]] && source "$HOME/.profile"

if [[ $( uname -s ) == "Linux" && -f "$HOME/.bashrc" ]]; then
    case "$-" in
        *i*) [[ -f "$HOME/.bashrc" ]] && . "$HOME/.bashrc" ;;
    esac
fi

if command -v rbenv > /dev/null 2>&1; then
    case ":$PATH:" in
        *":$HOME/.rbenv/shims:"*) ;;
        *) export PATH="$HOME/.rbenv/shims:$PATH" ;;
    esac
fi

[[ -f "$HOME/.bash_profile.local" ]] && source "$HOME/.bash_profile.local"
