# zshrc

export DISABLE_AUTO_UPDATE="true"
export ENABLE_CORRECTION="true"
export COMPLETION_WAITING_DOTS="true"
export HIST_STAMPS="yyyy-mm-dd"

setopt HIST_IGNORE_ALL_DUPS
setopt SH_FILE_EXPANSION
setopt EXTENDEDGLOB
setopt CSHNULLGLOB

autoload -U zmv

if [[ -d "$HOME/.oh-my-zsh" ]]; then
    plugins=(omz-git vb cdc osx sudo ruby rails zsh-autosuggestions
      per-directory-history history-substring-search fast-syntax-highlighting
      history-search-multi-word)
    export ZSH="$HOME/.oh-my-zsh"
    export ZSH_THEME="grayt"
    export ZSH_COMPDUMP=$ZSH_CACHE_DIR/zcompdump-$ZSH_VERSION
    source $ZSH/oh-my-zsh.sh
    bindkey -M emacs '^N' history-substring-search-down
    bindkey -M emacs '^P' history-substring-search-up
else
    [[ -d $HOME/.cache/zsh/ ]] || mkdir $HOME/.cache/zsh/
    export ZSH_COMPDUMP=$HOME/.cache/zsh/zcompdump-$ZSH_VERSION
fi

[[ -d $HOME/bin/lib/zsh ]] && fpath=($HOME/bin/lib/zsh $fpath)

() {
    local file
    for file { [[ -f $file ]] && source "$file" }
} $HOME/.opam/opam-init/init.zsh $HOME/.shellrc

[[ -f $HOME/.zshrc.local ]] && source $HOME/.zshrc.local

